# Generated by Django 3.2.8 on 2021-10-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
